### ISSUE TITLE
Feedback on Tutorial: Create a multitenant container database in `HANAExpress`

### ISSUE THREAD

**Issue by calle2010** [SAPDocuments/How-Tos#13]
For the CREATE DATABASE statement I receive error message

general error: Database could not be started;start databaseServer for database=3 on : hxehost:30040 failed 

select \* from "PUBLIC"."M_DATABASES"

returns ACTIVE_STATUS=NO for the new database.

Would be great if there was some help with trouble shooting in this tutorial.

**Comment by tonyZhou2014** [comment]
Database could not be started is a general error might due to many reasons.

You need to provide trace file and detail configuration/setup.

Give you an example here: If you only have 8GB memory, you tried to create the 3rd database (2nd tenantDB), then this might be expected behavior and you might see oom trace file in the trace folder.
